### PR TITLE
Bv command

### PR DESCRIPTION
**Pull request by sapetnioc**
The review of this PR is a way to eventually modify and validate the behavior of `bv` command. See #119

### CODE REVIEW

**Comment by denisri** [comment]
The `bv` script looks for `casa_distro` command in `<environment_dir>/bin/`. We have a setup script (in `share/scripts/casa_build_host_links`) which installs it in `<environment_dir>/host_bin/` to show that these executables are for host-side execution, but maybe it was not a good idea. Do I change the "install" dir to `bin`, or do we change the search path in `bv` to `host_bin` ?

**Comment by denisri** [comment]
Another question: `bv` looks for its environment dir as if it is installed in `<environment_dir>/bin/`. However it will actually be installed by the script inside the container, and `<environment_dir>/bin/` is not necessarily mounted from the container: only `<environment_dir>/host/` is. This is why we install run scripts in `<environment_dir>/host/host_bin/` (with `host/` subdirectory). It's a bit less convenient for the user, but it is the way files can be both seen from the host and installed from the container. Do we agree on using bv in `host/` ?

**Comment by denisri** [comment]
(if OK I have a working modif that can be pushed)

**Comment by sapetnioc** [comment]
I think `host_bin` is not necessary. It adds a directory to manage in user environments. We should use an already existing directory.

It is not yet clear to me where `bv` command and other host commands should be. It depends on the way everything is installed from scratch. We may manage  ̀bv` differently than other host command because it is not generated but installed with casa_distro (via pip for instance). This makes connections between several issues : #119, #144, #132 and #145.

In order to move forward step by step, I would validate this PR (and close #119) even if ̀`bv` is still a draft. The command will then be modified when working on the other issues.

**Comment by sapetnioc** [comment]
By the way, are the scripts will really be installed by a script inside the container ? I think they would be created by `casa_distro setup` that is running on the host.

**Comment by denisri** [comment]
> We should use an already existing directory.

But we don't have one, except this "`host_bin`" (see later)

>  I would validate this PR (and close #119) even if ̀bv is still a draft.

I completely agree - let's do that.

> are the scripts will really be installed by a script inside the container ?

I have done a script "`casa_build_host_links`" (in `share/scripts`) which is meant to run from inside the container and installs some programs for the host side. It mainly writes things in `<environment_dir>/host/host_bin` (this is why I was talking about this `host_bin` directory. It installs the following:
* casa-distro commands and python modules, `casa_distro` and `bv` commands: they are copied outside of the container insall/build directories in order to be visible from the host system, with their python libs. In "developer" container mode (the `src` and `build` directories are actually on the host system and are visible) we do symlinks there in order to benefit from modifs and updates from the developer.
* run scripts for all other brainvisa distribution commands (typically `brainvisa`, `anatomist`, `Aims*` etc: all which is found in `install/bin` or `build/bin` except "special" commands such as `bv_env`): they are shell scripts which wrap the call to `casa_distro` and call the command "transparently" in the container, so that the user runs them as if they were running on the host.

This `host_bin` directory thus needs to be visible from both the host and the container, because things are written there from the container, and will be used from the host. `host_bin` is perhaps not a very good name, we could chose to name it `bin`, but it has to be clear that things there should be used from the host. Anyway I think the `bv` script should be located there.

**Pull request merged**
