### PR TITLE
Merge 3.0 into the master branch

### PR DESCRIPTION
**Pull request by ylep**
Do we have any users of the current master branch (casa-distro 2)? If not, things may be easier if we merge the `3.0` branch and just continue to work on `master` from now on...

For instance, in every environment we have to manually switch the branch of `casa-distro` to `3.0` in order for `bv` to work correctly.

We can also wait and do it when we are ready for the actual release, I let you decide @sapetnioc @denisri.

### CODE REVIEW

**Comment by sapetnioc** [comment]
Yes, there are users. Almost all people who need to compile are using master branch. They would loose access to their 2.0 build workflow directories if we merge. At least, we must warn them in advance and write a procedure to manage the change. I think it is easier to manage the dev environement we create for now. Switch to 3.0 branch is a one time action and there is an explicit error message if it is not done. The main drawback is that `bv_maker` does not update the 3.0 branches sources.

**Comment by ylep** [comment]
Okay, let's turn this PR into a draft to prevent accidental merging, and keep it on the BrainVISA 5.0 release project.

**Comment by denisri** [comment]
So how do we proceed to warn people ?

**Comment by sapetnioc** [comment]
If we finally decide to merge, yes but I thought we decided to wait for the release. Anyway, I am investigating the potential impact of the merge for CATI developers. I proposed them to explicitely use a `2.0̀` branch (that we would create) to keep using casa_distro 2. If they think they can manage it, the warn and merge would be ok for me. But, I do not known how many people are using casa_distro outside CATI and how to contact them all.

**Comment by sapetnioc** [comment]
CATI team is ok for the merge. Moreover, they will soon use v 3.0 in production so they prefer that it is included in master. But what about other users ?

**Review by denisri — APPROVED** [review]
I'm OK with merging. We can manage people using v2 individually I guess.

**Comment by sapetnioc** [comment]
So let's prepare for merging. I already warn CATI. For me it is just a matter or creating a v2.0 branch from master then merging this PR. We should first merge other PRs in 3.0. Is there anything else ?

**Comment by ylep** [comment]
I just created the `2.0` branch. The existing PRs can either be merged, or we can change their base from `3.0` to `master` if we need more time before merging them.

**Review by sapetnioc — APPROVED** [review]

**Comment by sapetnioc** [comment]
Clear for take off

**Comment by ylep** [comment]
I just removed the requirement for Travis checks on `master` because we are out of Travis credits...

**Comment by ylep** [comment]
@sapetnioc À toi l’honneur :wink:

**Pull request merged**
